/**
 * Merkle tree construction, proof generation and verification.
 *
 * This implementation is deliberately byte-for-byte compatible with the
 * on-chain `MerkleVerifier.sol` verifier, and with `merkletreejs` configured
 * as `{ sortPairs: true }`. `packages/contracts/test/parity.test.ts` asserts
 * that compatibility against randomised trees on every test run, so the two
 * implementations cannot silently drift apart.
 *
 * Scheme: sorted-pair keccak256.
 *   - A parent hashes its two children concatenated in ascending byte order.
 *     Sorting means a proof carries no left/right flags, which keeps the
 *     on-chain verifier cheap.
 *   - A layer with an odd node count promotes the unpaired node unchanged to
 *     the next layer.
 *
 * SECURITY NOTE — second preimages. In a sorted-pair tree where leaves and
 * internal nodes are both 32 bytes, an internal node can be replayed as if it
 * were a leaf: presenting an internal node with the remaining proof path
 * verifies successfully. This is a known property of the scheme, not a bug in
 * this code, and it is why OpenZeppelin recommends hashing leaves twice. The
 * UI surfaces it rather than hiding it; see `isInternalNode` below, which lets
 * the Explorer warn when a "leaf" being verified is really a node.
 */

import { concatHex, keccak256, stringToHex } from 'viem';
import { type Hex, isHash32, normalizeHex } from './hex.js';

/**
 * Canonicalise a node value to lowercase 0x-hex, or null if it is not a
 * 32-byte hash. Every entry point runs its input through this: callers paste
 * hashes straight from explorers, which may use an uppercase `0X` prefix or
 * mixed-case digits, and the raw string would otherwise be concatenated
 * byte-wrong.
 */
function canon(value: string): Hex | null {
  const normalized = normalizeHex(value);
  return normalized !== null && isHash32(normalized) ? normalized : null;
}

/** Where a leaf sits in `layers`. */
export interface LeafPosition {
  readonly layer: number;
  readonly index: number;
}

/**
 * How a tree was assembled. The two schemes produce different roots for any
 * leaf count that is not a power of two, so a root is only meaningful next to
 * the scheme that built it.
 *
 *   layered   this project and `MerkleVerifier.sol`: pair up each layer, and
 *             promote an unpaired node unchanged. Every leaf sits on layer 0.
 *   standard  OpenZeppelin `StandardMerkleTree`: a complete binary tree in a
 *             flat array, leaves filling the last n slots in descending hash
 *             order. Leaves can therefore sit on two different layers.
 */
export type TreeScheme = 'layered' | 'standard';

export interface MerkleTree {
  /**
   * Bottom-up: the deepest layer first, the single root last. A node at
   * `layers[l][i]` has its parent at `layers[l + 1][Math.floor(i / 2)]` under
   * both schemes, which is what lets one renderer and one proof walk serve
   * either.
   */
  readonly layers: readonly (readonly Hex[])[];
  readonly root: Hex;
  /** Leaves in tree order, which is not input order under `standard`. */
  readonly leaves: readonly Hex[];
  /** `leafPositions[i]` locates `leaves[i]` in `layers`. */
  readonly leafPositions: readonly LeafPosition[];
  readonly scheme: TreeScheme;
}

export class MerkleError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'MerkleError';
  }
}

/** Hash two sibling nodes into their parent, concatenated in ascending order. */
export function hashPair(a: Hex, b: Hex): Hex {
  const left = normalizeHex(a);
  const right = normalizeHex(b);
  if (left === null || right === null) {
    throw new MerkleError('hashPair requires two hex values.');
  }
  const [lo, hi] = left <= right ? [left, right] : [right, left];
  return keccak256(concatHex([lo, hi]));
}

/**
 * Hash an arbitrary value into a 32-byte leaf.
 *
 * Hex input is decoded and its bytes are hashed; anything else is hashed as
 * UTF-8. This matches what `ethers`/`viem` do, and what the `keccak256` npm
 * package does, so leaves generated by any of them agree.
 */
export function hashLeaf(value: string): Hex {
  const asHex = normalizeHex(value);
  return keccak256(asHex ?? stringToHex(value));
}

/**
 * Build a tree from pre-hashed 32-byte leaves.
 * @throws MerkleError if the set is empty or any leaf is not 32-byte hex.
 */
export function buildMerkleTree(leaves: readonly Hex[]): MerkleTree {
  if (leaves.length === 0) {
    throw new MerkleError('Cannot build a Merkle tree with no leaves.');
  }
  const normalized = leaves.map((leaf, i) => {
    const value = canon(leaf);
    if (value === null) {
      throw new MerkleError(`Leaf at index ${i} is not a 32-byte hex value.`);
    }
    return value;
  });
  const layers: Hex[][] = [normalized];

  let current: Hex[] = normalized;
  while (current.length > 1) {
    const next: Hex[] = [];
    for (let i = 0; i < current.length; i += 2) {
      const left = current[i]!;
      const right = current[i + 1];
      // Odd node out: promote it unchanged rather than pairing it with itself.
      next.push(right === undefined ? left : hashPair(left, right));
    }
    layers.push(next);
    current = next;
  }

  return {
    layers,
    root: current[0]!,
    leaves: normalized,
    // Every leaf is on layer 0 under this scheme.
    leafPositions: normalized.map((_, index) => ({ layer: 0, index })),
    scheme: 'layered',
  };
}

/** Convenience: hash raw values into leaves, then build. */
export function buildTreeFromValues(values: readonly string[]): MerkleTree {
  return buildMerkleTree(values.map(hashLeaf));
}

/**
 * Sibling hashes proving `index` is in the tree, ordered leaf-upward.
 * A promoted odd node contributes no sibling at that layer, so proof length
 * is not always ceil(log2(n)).
 */
export function getProof(tree: MerkleTree, index: number): Hex[] {
  if (!Number.isInteger(index) || index < 0 || index >= tree.leaves.length) {
    throw new MerkleError(
      `Leaf index ${index} is out of range (tree has ${tree.leaves.length} leaves).`,
    );
  }

  // Start at the leaf's own layer. Under `layered` that is always 0; under
  // `standard` a leaf may sit one layer above the deepest.
  const start = tree.leafPositions[index]!;
  const proof: Hex[] = [];
  let idx = start.index;
  for (let level = start.layer; level < tree.layers.length - 1; level += 1) {
    const layer = tree.layers[level]!;
    const siblingIdx = idx % 2 === 0 ? idx + 1 : idx - 1;
    const sibling = layer[siblingIdx];
    if (sibling !== undefined) proof.push(sibling);
    idx = Math.floor(idx / 2);
  }
  return proof;
}

/** Find a leaf's index, or -1. Comparison is case-insensitive. */
export function indexOfLeaf(tree: MerkleTree, leaf: Hex): number {
  const target = canon(leaf);
  if (target === null) return -1;
  return tree.leaves.findIndex((l) => l === target);
}

/**
 * Fold a proof from `leaf` up to a root. Mirrors `MerkleVerifier._verify`.
 * Pure and total: malformed input yields a non-matching root, never a throw.
 */
export function processProof(leaf: Hex, proof: readonly Hex[]): Hex {
  let computed = canon(leaf);
  if (computed === null) throw new MerkleError('Leaf is not a 32-byte hex value.');
  for (const element of proof) {
    const sibling = canon(element);
    if (sibling === null) throw new MerkleError('Proof element is not a 32-byte hex value.');
    computed = hashPair(computed, sibling);
  }
  return computed;
}

/** True if `proof` proves `leaf` is under `root`. */
export function verifyProof(leaf: Hex, proof: readonly Hex[], root: Hex): boolean {
  const canonLeaf = canon(leaf);
  const canonRoot = canon(root);
  if (canonLeaf === null || canonRoot === null) return false;
  if (!proof.every((p) => canon(p) !== null)) return false;
  return processProof(canonLeaf, proof) === canonRoot;
}

/**
 * True if `value` appears as an internal (non-leaf) node.
 *
 * Powers the second-preimage warning described in the file header: a caller
 * can verify an internal node as though it were a leaf, and the UI says so.
 */
export function isInternalNode(tree: MerkleTree, value: Hex): boolean {
  const target = canon(value);
  if (target === null) return false;
  return tree.layers.slice(1).some((layer) => layer.some((node) => node === target));
}

/** Total node count across every layer — used by the visualisation. */
export function nodeCount(tree: MerkleTree): number {
  return tree.layers.reduce((sum, layer) => sum + layer.length, 0);
}

/**
 * Build a tree the way OpenZeppelin's `StandardMerkleTree` does.
 *
 * The layout is a complete binary tree in a flat array of `2n - 1` entries:
 * leaves occupy the last `n` slots in descending hash order, and the node at
 * array index `i` is `hashPair(a[2i + 1], a[2i + 2])`. That differs from
 * `buildMerkleTree`, which pairs whole layers and promotes an unpaired node --
 * the two agree only when the leaf count is a power of two.
 *
 * `leaves.test.ts` asserts root-and-proof equality against the real
 * `@openzeppelin/merkle-tree` package, and that OpenZeppelin's own verifier
 * accepts the proofs produced here.
 *
 * @param leaves already-hashed 32-byte leaves, in any order; this sorts them.
 * @throws MerkleError if the set is empty or any leaf is not 32-byte hex.
 */
export function buildStandardMerkleTree(leaves: readonly Hex[]): MerkleTree {
  if (leaves.length === 0) {
    throw new MerkleError('Cannot build a Merkle tree with no leaves.');
  }
  const normalized = leaves.map((leaf, i) => {
    const value = canon(leaf);
    if (value === null) {
      throw new MerkleError(`Leaf at index ${i} is not a 32-byte hex value.`);
    }
    return value;
  });

  const n = normalized.length;
  // Descending: hashes are fixed-width lowercase hex, so string order is byte order.
  const sorted = [...normalized].sort((a, b) => (a < b ? 1 : a > b ? -1 : 0));

  const nodes: (Hex | undefined)[] = new Array(2 * n - 1).fill(undefined);
  for (let i = 0; i < n; i += 1) nodes[n - 1 + i] = sorted[i]!;
  for (let i = n - 2; i >= 0; i -= 1) {
    nodes[i] = hashPair(nodes[2 * i + 1]!, nodes[2 * i + 2]!);
  }

  // Slice the array into depth levels, then reverse so the deepest comes first
  // and `layers[l][i]`'s parent stays at `layers[l + 1][floor(i / 2)]`.
  const levels: Hex[][] = [];
  for (let start = 0; start < nodes.length; start = 2 * start + 1) {
    const end = Math.min(2 * start + 1, nodes.length);
    levels.push(nodes.slice(start, end) as Hex[]);
  }
  const layers = levels.reverse();

  // A leaf's array index maps to (depth, offset within that depth).
  const depthOf = (arrayIndex: number) => Math.floor(Math.log2(arrayIndex + 1));
  const leafPositions = sorted.map((_, i) => {
    const arrayIndex = n - 1 + i;
    const depth = depthOf(arrayIndex);
    return {
      layer: layers.length - 1 - depth,
      index: arrayIndex - (2 ** depth - 1),
    };
  });

  return { layers, root: nodes[0]!, leaves: sorted, leafPositions, scheme: 'standard' };
}
